import React from "react";
import AnimatedText from "../components/AnimatedText";
import Link from "next/link";
import { FramImage } from "../components/FrameImage";
import { MovingImage } from "../components/MovingImage";
import HtmlCssImg from "../../public/Html&Css.jpg";
import jspic from "../../public/jspic.jpg";
import Reactpic from "../../public/reactpic.jpg";
import Nextpic from "../../public/nextpic.jpg";

export const metadata = {
  title: "Articles",
  description: "Generated by create next app",
};

const FuteredArricall = ({ img, title, time, summary, link }) => {
  return (
    <li className="col-span-1 w-full p-4 bg-gradient-to-b from-gray-700 to-black border border-solid border-black text-white rounded-2xl">
      <Link
        href={link}
        target="-blank"
        className="w-full inline-block cursor-pointer overflow-hidden rounded-lg"
      >
        <FramImage
          src={img}
          alt={title}
          className="w-full h-auto"
          whileHover={{ scale: 1.05 }}
          transition={{ duration: 0.2 }}
        />
      </Link>
      <Link href={link} target="-blank">
        <h2 className=" capitalize text-2xl font-bold my-2 mt-4 hover:underline">
          {title}
        </h2>
      </Link>
      <p className=" text-sm mb-2">{summary}</p>
      <span className=" text-purple-500 font-semibold xs:text-lg">{time} </span>
    </li>
  );
};

const AllArticals = ({ img, title, date, link }) => {
  return (
    <li
      className=" relative w-full p-4 py-6 my-4 rounded-xl flex 
     items-center justify-between bg-gradient-to-b from-gray-700 to-black text-white first:mt-0 
      border border-solid border-black border-r-4 border-b-4
    "
    >
      <MovingImage title={title} img={img} alt={title} link={link} />
      <span className=" text-sky-400 font-semibold pl-4">{date} </span>
    </li>
  );
};

export default function Art() {
  return (
    <div className="w-full h-full inline-block z-0 bg-gradient-to-b from-gray-700 to-gray-900 p-32 pt-0 xs:px-7">
      <main className="flex w-full flex-col items-center justify-center pt-5 mb-16 mt-6">
        <AnimatedText
          text="Words Can Change The World! "
          className="text-center  mb-16 lg:!text-7xl sm:mb-8 sm:!text-6xl xs:!text-4xl"
        />
        <ul className="grid grid-cols-2 gap-16 lg:gap-8 md:grid-cols-1 md:gap-y-16 ">
          <FuteredArricall
            title=" HTML5 and CSS3 "
            summary="The Dynamic Duo Transforming Web Design."
            time="10 min read"
            link="/Art/HtmlAndCss"
            img={HtmlCssImg}
          />
          <FuteredArricall
            title="The Power and Versatility of JavaScript "
            summary=" A Comprehensive Guide . "
            time="15 min read"
            link="/Art/JavaScript"
            img={jspic}
          />
        </ul>
        <h2 className=" font-bold text-4xl w-full text-center my-16 mt-32 text-white">
          {" "}
          All Articals{" "}
        </h2>
        <ul className=" w-full">
          <AllArticals
            title="React.js : Revolutionizing Web Development with Component-Based Architecture "
            date="Septamper 20,2023"
            link="/Art/Reactjs"
            img={Reactpic}
          />
          <AllArticals
            title="Next.js : Unlocking the Future of Web Development"
            date="Septamper 20,2023"
            link="/Art/NextJs"
            img={Nextpic}
          />
        </ul>
      </main>
    </div>
  );
}
