import React from 'react'
import AnimatedText from '../components/AnimatedText'
import Link from 'next/link'
import { GithubIcon } from '../components/icons/github'
import Homepro from '../../public/homepro.png'
import { FramImage } from '../components/FrameImage'

export const metadata = {
  title: 'Projects',
  description: 'Generated by create next app',
}



const FeatureProject =({type,title,summary,img,link,github})=>{

  return(
    <article 
    className='w-full flex items-center justify-between text-white
     rounded-3xl border border-solid border-black bg-black shadow-2xl p-12
       lg:flex-col lg:p-8 xs:rounded-2xl  xs:p-4
    '>

      <Link href={link} target='-blank'
      className='w-1/2 cursor-pointer overflow-hidden rounded-lg lg:w-full'
      >
        <FramImage src={img} alt={title} className='w-full h-auto'
        whileHover={{scale:1.05}}
        transition={{duration:0.2}}
        />
      </Link>
      <div className='w-1/2 flex flex-col items-start justify-between pl-6 lg:w-full lg:pl-0 lg:pt-6'>
          <span className=' text-red-500 font-medium text-xl  xs:text-base '>{type}</span>
          <Link href={link} target='-blank' className=' hover:underline underline-offset-2 '>
          <h2 className='my-2 w-full text-left text-4xl font-bold text-white sm:text-sm '>{title}</h2>
          </Link>
          <p className=' my-2 font-medium text-white sm:text-sm'>{summary}</p>
        <div className='mt-2 flex items-center'>
            <Link href={github} target='-blank' className=' w-10'>
              {''} <GithubIcon/> {''} 
            </Link>
            <Link href={link} target='-blank' 
            className=' ml-4 rounded-lg bg-black text-white p-2 px-6 text-lg font-semibold 
            sm:px-4 sm:text-base '>
              
               Visitr Project</Link>
        </div>
      </div>


    </article>
  )
}

const Projectt =({title,type,img,link,github})=>{
  return(
    <article className='w-full flex flex-col items-center justify-center rounded-2xl 
    border border-solid border-black bg-black text-white p-6 relative
     xs:p-4'>
      <Link href={link} target='-blank'
      className='w-full cursor-pointer overflow-hidden rounded-lg'
      >
      <FramImage src={img} alt={title} className='w-full h-auto'
      whileHover={{scale:1.05}}
      transition={{duration:0.2}}
      />
      </Link>
      <div className='w-full flex flex-col items-start justify-between mt-4 '>
          <span className=' text-red-500 font-medium text-xl lg:text-lg  md:text-base '>{type}</span>
          <Link href={link} target='-blank' className=' hover:underline underline-offset-2 '>
          <h2 className='my-2 w-full text-left text-3xl font-bold lg:text-2xl  '>{title}</h2>
          </Link>
        <div className=' w-full mt-2 flex items-center justify-between'>
          <Link 
          href={link} 
          target='-blank' 
          className='text-lg font-semibold underline md:text-base'>
            Visitr
          </Link>
          <Link href={github} target='-blank' 
            className=' w-8 md:w-6'>
            <GithubIcon/> {''} 
          </Link>

        </div>
      </div>



    </article>

  )
}






export default function Projects() {
  return (
    <div className="w-full h-full inline-block z-0 bg-gradient-to-b from-gray-700 to-gray-900 p-32 pt-0 xs:px-7">
      <main className="flex w-full flex-col items-center justify-center pt-5 mb-16 mt-6">
        <AnimatedText text='Imagination Trumps Knowledge!'
        className="text-center mb-16 lg:!text-7xl sm:mb-8 sm:!text-6xl xs:!text-4xl   "
        />

        <div className=' grid grid-col-12 gap-24 gap-y-32 xl:gap-x-16 lg:gap-x-8 md:gap-y-24 sm:gap-x-0 '>
          
          <div className=' col-span-12'> 
            <FeatureProject
            title='Lettel Lemon Resurant '
            img={Homepro}
             summary='A project made by React JS it is demmand from meta to acomplich the certifecat '
            link='https://github.com/HusseiN18779/LEttelLemon'
            github='https://github.com/HusseiN18779/LEttelLemon'
            type='Featured Project'
            />
          </div>
          <div className=' col-span-6 sm:col-span-12'>
          <Projectt
            title='Crypto Screener Application'
            img={Homepro}
            link='/'
            github='/'
            type='Featured Project'
            />
          </div>
          <div className=' col-span-6 sm:col-span-12'>
          <Projectt
            title='Crypto Screener Application'
            img={Homepro}
            link='/'
            github='/'
            type='Featured Project'
            />
          </div>

        </div>
      </main>
    </div>
  )
}
