import React from "react";
import AnimatedText from "@/app/components/AnimatedText";
import Image from "next/image";
import HTml5Css3Img from "../../../public/Html&Css.jpg";

export const metadata = {
  title: "Articles",
  description: "Generated by create next app",
};

export default function HtmlAndCss() {
  return (
    <div className="w-full h-full inline-block z-0 bg-gradient-to-b from-gray-700 to-gray-900 p-32 pt-0 xs:px-7">
      <main className="grid w-full  items-center justify-center pt-5 mb-16 mt-6">
        <AnimatedText
          text="HTML5 & CSS3 ! "
          className="text-center  mb-16 lg:!text-7xl sm:mb-8 sm:!text-6xl xs:!text-4xl"
        />
        <div>
          <div>
            <Image
              src={HTml5Css3Img}
              alt="hussein"
              className="w-full h-auto rounded-2xl "
            />
          </div>

          <div>
            <article className="text-white">
              <h2 className=" font-bold text-4xl my-6 text-center">
                The Dynamic Duo Transforming Web Design
              </h2>
              <h3 className="my-3 font-bold text-4xl"> Introduction</h3>
              <span>
                In the ever-evolving realm of web development, HTML5 and CSS3
                have emerged as a dynamic duo that has revolutionized the way
                websites are designed and presented to users. HTML5, the latest
                version of the Hypertext Markup Language, and CSS3, the latest
                version of Cascading Style Sheets, have ushered in a new era of
                web design by offering powerful features, enhanced capabilities,
                and improved user experiences. In this article, we will delve
                into the synergistic relationship between HTML5 and CSS3 and
                explore how they are reshaping the web.
              </span>
              <h3 className="my-3 font-bold text-xl">
                1. Semantic Structure with HTML5
              </h3>
              <span>
                HTML5 is not just a markup language; it's a structural
                masterpiece. It introduces a plethora of semantic elements like
                header nav, main,section, article, and footer, which provide a
                clear and meaningful way to structure web content. These
                elements not only improve website organization but also benefit
                accessibility and search engine optimization SEO. By utilizing
                semantic HTML5 tags, web developers can create cleaner, more
                maintainable code that is easier to understand and navigate.
              </span>
              <h3 className="my-3 font-bold text-xl">
                2. Rich Media Integration
              </h3>
              HTML5 has transformed the way we incorporate multimedia elements
              into web pages. With the `video` and `audio` elements, developers
              can seamlessly embed videos and audio clips, eliminating the need
              for third-party plugins like Adobe Flash. These native elements
              ensure cross-browser compatibility and accessibility, providing a
              smoother and more engaging user experience.
              <h3 className="my-3 font-bold text-xl">
                3. Responsive Web Design
              </h3>
              <span>
                In the age of mobile devices, responsive web design is
                paramount. HTML5, in conjunction with CSS3, has made responsive
                design more accessible and efficient. Media queries, a feature
                of CSS3, allow developers to apply different styles based on the
                screen size and orientation. This ensures that websites adapt
                seamlessly to various devices, from desktop monitors to
                smartphones and tablets.
              </span>
              <h3 className="my-3 font-bold text-xl">
                4. CSS3 Transforms and Animations
              </h3>
              <span>
                CSS3 introduces transformative power to web design with its
                extensive suite of transformation and animation properties.
                Developers can easily apply effects such as rotations, scaling,
                skewing, and translations to HTML elements, creating visually
                stunning interfaces and animations without the need for
                JavaScript or complex libraries. CSS3 animations have brought
                life to websites, making user interactions more engaging and
                delightful.
              </span>
              <h3 className="my-3 font-bold text-xl">
                5. Customized Styling and Layouts
              </h3>
              <span>
                CSS3 takes styling to the next level by offering advanced
                features like custom fonts, gradients, shadows, and flexible box
                layouts. It enables designers to exercise creative freedom,
                resulting in unique and visually appealing web pages. The
                flexibility of CSS3 ensures that web designers can achieve their
                desired aesthetics and layouts with ease.
              </span>
              <h3 className="my-3 font-bold text-xl">
                6. Transition and Flexibility
              </h3>
              <span>
                {" "}
                CSS3 transitions and flexbox layouts provide dynamic control
                over how elements change from one state to another and how
                content is arranged within containers. These features streamline
                the development process and make it easier to create modern,
                interactive web applications.
              </span>
              <h2 className=" text-center my-6 text-6xl font-bold ">
                {" "}
                Conclusion
              </h2>
              <span>
                HTML5 and CSS3 are the dynamic duo that has reshaped web design
                and development. HTML5's semantic structure and multimedia
                integration have improved content organization and user
                engagement, while CSS3's transformative and styling capabilities
                have elevated the aesthetics and functionality of websites.
                Together, they have enabled responsive design, dynamic
                animations, and customized layouts that cater to the diverse
                needs of the modern web. As web technologies continue to evolve,
                HTML5 and CSS3 remain at the forefront, empowering web
                developers and designers to create visually stunning,
                accessible, and responsive websites. Their collaborative efforts
                ensure that the web continues to evolve into a platform that
                delivers outstanding user experiences across a wide range of
                devices and screen sizes. Whether you're a seasoned web
                professional or a budding developer, mastering HTML5 and CSS3 is
                essential for staying at the forefront of web design innovation.
              </span>
              <h3 className="text-4xl pt-20 text-center">
                Thanks For Reading .
              </h3>
            </article>
          </div>
        </div>
      </main>
    </div>
  );
}
